### ISSUE TITLE
Ignore extension

### ISSUE THREAD

**Issue by AckslD** [jiro-aqua/aGrep#8]
I want to search all files (ignore extension). Clicking "no extension" under "add extensions" gives the `*`-option. I read this as "match all file extensions" but it seems it only match files without any extension at all. Is this the intended behaviour?

**Comment by Trasd** [comment]
It seems to be.  I edited the code and put an "All Extensions" in the dialog box, then changed how it handles extensions for that option.  It was years ago, but it still works.

I also upgraded the version and imported it to a more "Studio" appropriate layout, but it's all in AIDE, so it doesn't use Jetpack.  As my main device is running 5.x, it is fine for me.  If you give me a way, I can get the APK (and or code) to you.

Since Google announced it's going with the SAF only, I quite working on it.

**Comment by jiro-aqua** [comment]
Hi, Thanks for both of you.

But this app was designed for legacy Android platform and has no role on modern Android.
So I no longer maintain this app and upload new version to Play Store.

Please fork it by yourself and modify as you like under the license.

**Comment by Trasd** [comment]
jiro

Understood.  I've updated the code already and was just letting him know.  But, I do appreciate you releasing it in the first place.

**Comment by jiro-aqua** [comment]
Trasd

I can understand.
But 5 years has passed from last release of this app,
A lot of things had changed about Android App Development.
- Eclipse to Android Studio.
- Activity to AndroidX.
- Runtime permission.
- Scoped Storage.
- targetSdk limitation.
- etc. etc.

I can fix above issues, but the deliverable will be a just useless app.

So you should better to build by yourself.

p.s. BTW I'm glad to hear both of you like my old app. Thanks!

**Comment by Trasd** [comment]
jiro

That's what I'm telling you (and AckslD)!

I've already (re)built it myself.  Nothing is required of you.

I have already made the changes he's requesting.  I did it years ago.

You do not need to fix anything!  I was letting him know I can send him the code and or the APK that I've already built!

**Comment by AckslD** [comment]
Thanks for the information @jiro-aqua @Trasd! I hadn't realised that this app was developed so long ago :) Anyway, even though it's old it does what I want :+1:
